version: '3.8'

services:
  reddit-mcp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MCP_TRANSPORT=streamable-http
      - PORT=8080
      # Add your Reddit API credentials here for testing
      # Or pass them as query parameters in the request
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=RedditResearchMCP/1.0 (Docker Test)
    volumes:
      # Mount for development (optional - comment out for production-like testing)
      - ./src:/app/src:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s